dist: trusty
language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "tanichols-github"
    token: $sonar_token
cache:
  directories:
  - node_modules
script:
  - npm run cover
  - npm run build
  - sonar-scanner
deploy:
  provider: heroku
  api_key: $heroku_token
  app: rental-property-advisor
